steps:
  - name: gradle:5.6.2-jdk8
    entrypoint: gradle
    args: ["test"]
  - name: gradle:5.6.2-jdk8
    entrypoint: gradle
    args: ["assemble"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/hello-spring", "--build-arg=JAR_FILE=build/libs/hellospring-1.0.0.jar", "."]
images: ["gcr.io/$PROJECT_ID/hello-spring"]
